City-of-Helsinki/drupal-helfi-tyollisyyspalvelut-manuaali

composer.json
config/sync/core.entity_form_display.message.hel_tpm_update_reminder.default.yml
config/sync/core.entity_view_display.message.hel_tpm_update_reminder.default.yml
config/sync/core.entity_view_display.message.hel_tpm_update_reminder.mail_body.yml
config/sync/core.entity_view_display.message.hel_tpm_update_reminder.mail_subject.yml
config/sync/core.extension.yml
config/sync/language/fi/message.template.hel_tpm_update_reminder.yml
config/sync/message.template.hel_tpm_update_reminder.yml
public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.info.yml
public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.module

drush cim
1. Change the $ago condition to days or weeks.
2. Run drush cron twice. If you have any over day-old service nodes the first run should send a reminder email to the author (captured by Mailhog), the second one should find the node but not send another email.

TP-67: Update reminder

---

config/sync/search_api.index.service_search_index.yml
config/sync/views.view.content.yml
config/sync/views.view.service_search.yml
config/sync/views.view.services.yml
config/sync/workflows.workflow.service_moderation.yml
public/modules/custom/hel_tpm_editorial/hel_tpm_editorial.module

TP-163: Add an ”on hold” status to the services

---

config/sync/search_api_autocomplete.search.solr_service_search.yml

Changed minimum keyword length for autocomplete

---

config/sync/core.entity_form_display.node.service.default.yml

Changed some of untranslatable the paragraph field widgets to ief

---

config/sync/group.role.organisation-administrator.yml
config/sync/group.role.organisation-editor.yml
config/sync/group.role.organisation-expert.yml
config/sync/group.role.service_provider-editor.yml
config/sync/group.role.service_provider-group_admin.yml
config/sync/group.role.service_provider-member.yml
config/sync/group.role.service_provider-organization_ad.yml
config/sync/views.view.group_invitations.yml
config/sync/views.view.group_members.yml
config/sync/views.view.group_service_locations.yml
config/sync/views.view.group_services.yml

**Notes/Bugs:**
- User permissions are inherited from parent group, so if the user has privileges in Organization they'll also have them in the Service provider.
- Block "Tuottamamme palvelut" should be visible for Service provider users on the first tab, but isn't?

TP-851: Change role permissions and views access

---

config/sync/views.view.group_invitations.yml

TP-890 disallowed group invitations tabs from other that admin and root roles

---

config/sync/language/en/views.view.group_subgroup_services.yml
config/sync/language/sv/views.view.group_subgroup_services.yml
config/sync/views.view.group_subgroup_services.yml

TP-882 refactored subgroup services to list groups responsibility services

---

composer.json
composer.lock

lando composer install && lando drush cr 

TP-928 patched paragraphs legacy to always show default form even when entity is saved without value.

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.module
translations/fi-interface-translations.po

As requested, add additional error message when saving a service and the age groups and age range fields are not filled.
drush cr

TP-970 Add additional error message for age groups

---

config/sync/views.view.group_responsibility_services.yml

There were an error while trying to get the group ID from the URL during ajax call. It was decided that the broken filter is not needed at least for now, so removing it.
drush cim
drush cr

Fix group responsibility services view

---

public/modules/custom/service_manual_workflow/src/EventSubscriber/ServiceStateChangedNotificationSubscriber.php

TP-990 added rtb notification sending when moving service from published and outdated to ready to publish state

---

config/sync/user.role.specialist.yml

TP-951 Add contact info view permission for specialists

---

config/sync/autologout.settings.yml

TP-1036 raised autologout limit to 8 hours and confirmation popup to 1m

---

config/sync/autologout.settings.yml

TP-1040 Raise logout dialog respond time

---

config/sync/views.view.maintenance_and_administration.yml

TP-1093 Do not allow content admin view for specialist users

---

config/sync/language/en/views.view.admin_people_by_group.yml
config/sync/views.view.admin_people_by_group.yml
public/modules/custom/hel_tpm_group/config/schema/hel_tpm_group.schema.yml
public/modules/custom/hel_tpm_group/hel_tpm_group.module
public/modules/custom/hel_tpm_group/src/Plugin/views/filter/GroupLabel.php

TP-1002 Add people list with group info for admins

---

public/modules/custom/service_manual_workflow/tests/src/ExistingSite/ServicePopupConfirmSettingsFormTest.php

TP-1073 Add ExistingSite test for service popup settings form

---

public/themes/custom/palvelumanuaali/templates/fields/field--paragraph--field-description--service-price.html.twig

`Drush cr`
Add template for price description field in service description.
(so that the text is properly wrapped)

TP-1177 Add wrapper for the price description field

---

config/sync/views.view.solr_service_search.yml
public/modules/custom/hel_tpm_search/src/Plugin/views/filter/AgeGroups.php
translations/fi-interface-translations.po
translations/sv-interface-translations.po

TP-1171 Change age filter's age ranges

---

config/sync/language/en/views.view.group_members.yml
config/sync/language/sv/views.view.group_members.yml
config/sync/user.role.admin.yml
config/sync/user.role.editor.yml
config/sync/user.role.specialist_editor.yml
config/sync/views.view.group_members.yml
public/modules/custom/hel_tpm_group/hel_tpm_group.module
public/modules/custom/hel_tpm_group/hel_tpm_group.permissions.yml

Adds account status column to group members lists. Allows group admins to see the members' status field (which is not allowed by default).
drush deploy

TP-965 Show account status at group members list

---

config/sync/views.view.maintenance_and_administration.yml

TP-982 adjust maintenance view group pathing

---

public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldFormatter/TimeAndPlaceFormatter.php
public/themes/custom/palvelumanuaali/templates/paragraphs/paragraph--service-time-and-place.html.twig
translations/fi-interface-translations.po
translations/sv-interface-translations.po

```
lando drush -y locale:import fi ../translations/fi-interface-translations.po
lando drush -y locale:import sv ../translations/sv-interface-translations.po
lando drush cr
```
Fixes issue where date and place element won't be shown when location is not chosen.
If location or date is chosen, the box should be displayed

TP-1229 Adjust date place text logic

---

config/sync/field.field.node.service.field_responsible_updatee.yml
public/modules/custom/service_manual_workflow/service_manual_workflow.module

TP-1260 Require field_responsible_updatee on publish

---

public/themes/custom/palvelumanuaali/palvelumanuaali.libraries.yml
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

drush deploy
When checking the script, try to find `matomo.js` from source.

TP-1176 Exclude analytics from admin users and user pages

---

config/sync/autologout.role.specialist.yml
config/sync/autologout.settings.yml

TP-1270 Log out specialists after two weeks of inactivity

---

config/sync/core.entity_view_display.message.hel_tpm_user_expiry_blocked.mail_body.yml
config/sync/core.entity_view_display.message.hel_tpm_user_expiry_blocked.mail_subject.yml
config/sync/language/fi/message.template.1st_user_account_expiry_reminder.yml
config/sync/language/fi/message.template.2nd_user_account_expiry_reminder.yml
config/sync/language/fi/message.template.hel_tpm_user_expiry_blocked.yml
config/sync/message.template.1st_user_account_expiry_reminder.yml
config/sync/message.template.2nd_user_account_expiry_reminder.yml
config/sync/message.template.hel_tpm_user_expiry_blocked.yml
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module
public/modules/custom/hel_tpm_user_expiry/src/Plugin/QueueWorker/UserExpirationNotification.php
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.field.user.user.field_employer.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.field.user.user.field_job_title.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.field.user.user.field_name.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.storage.user.field_employer.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.storage.user.field_job_title.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/field.storage.user.field_name.yml
public/modules/custom/hel_tpm_user_expiry/tests/modules/hel_tpm_user_expiry_messages_test/config/install/message.template.hel_tpm_user_expiry_blocked.yml
public/modules/custom/hel_tpm_user_expiry/tests/src/Kernel/UserExpirationTest.php

**Description:**
* Updates reminder messages.
* Adds new message for account deactivation.
* Anonymizes accounts 30 days after deactivation.
For manual testing, you need to alter timestamps in database:
Preparations for local testing environment:
Running cron:
Run automated tests:

TP-537 User expiry

---

public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module

TP-1331 Delete user expiry state when unblocking user

---

public/themes/custom/palvelumanuaali/templates/fields/field--field-service-languages--paragraph--limited-fields.html.twig
public/themes/custom/palvelumanuaali/templates/fields/field--field-service-languages--paragraph--taxonomy-card.html.twig

TP-1334 Fix twig template rendering language field in taxonomy views

---

config/sync/language/en/views.view.group_services.yml
config/sync/language/sv/views.view.group_services.yml
config/sync/views.view.group_services.yml

Hotfix TP-1349 Reverted service view reponsibile editors to not use

---

public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.module
public/modules/custom/hel_tpm_update_reminder/src/UpdateReminderUtility.php
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.content_has_been_published.field_message_author.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.content_has_been_published.field_node.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.content_has_been_published.field_user.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.hel_tpm_update_reminder_outdated.field_node.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.hel_tpm_update_reminder_outdated.field_user.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.hel_tpm_update_reminder_service.field_node.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.message.hel_tpm_update_reminder_service.field_user.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.node.service.field_responsible_updatee.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.field.node.service.field_service_provider_updatee.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.storage.message.field_message_author.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.storage.message.field_node.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.storage.message.field_user.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.storage.node.field_responsible_updatee.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/field.storage.node.field_service_provider_updatee.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/message.template.content_has_been_published.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/message.template.hel_tpm_update_reminder_outdated.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/message.template.hel_tpm_update_reminder_service.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/node.type.service.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/config/install/workflows.workflow.service_moderation.yml
public/modules/custom/hel_tpm_update_reminder/tests/modules/hel_tpm_update_reminder_test/hel_tpm_update_reminder_test.info.yml
public/modules/custom/hel_tpm_update_reminder/tests/src/Kernel/ServiceUpdateReminderTest.php

Also fixes an entity query crash when there are no published services.

TP-1070 Add tests for hel_tpm_update_reminder module

---

public/themes/custom/palvelumanuaali/js/matomo.js

drush deploy
Before testing, note that the script is still not included for `/user` paths and admin users.

TP-1294 Disable tracking cookies

---

public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module
public/modules/custom/hel_tpm_user_expiry/tests/src/Kernel/UserExpirationTest.php

TP-1359 Added access time for re-activated users to avoid blocking.

---

config/sync/field.field.taxonomy_term.municipality.field_view_header.yml

TP-1400 Allow translating municipality taxonomy's view headers

---

public/modules/custom/hel_tpm_search/src/Plugin/better_exposed_filters/filter/DropdownMultiselect.php

TP-1435 Preserve parent category order

---

config/sync/views.view.group_members.yml

With ajax, a group admin without "administer users" permission was not able too see a user status field.
drush deploy

TP-1491: Disable ajax from group members view

---

config/sync/field.field.paragraph.service_time_and_place.field_dates.yml

TP-1522 Do not use default start date value

---

config/sync/core.base_field_override.group.organisation.label.yml
config/sync/core.base_field_override.group.service_provider.label.yml
config/sync/core.entity_form_display.group_content.group_content_type_a689b6d6f98cc.default.yml
config/sync/core.entity_form_display.group_content.organisation-group_membership.default.yml
config/sync/core.entity_view_display.group_content.group_content_type_a689b6d6f98cc.default.yml
config/sync/core.entity_view_display.group_content.organisation-group_membership.default.yml
config/sync/group.role.organisation-insider_root.yml
config/sync/group.role.service_provider-anonymous.yml
config/sync/group.role.service_provider-editor.yml
config/sync/group.role.service_provider-group_admin.yml
config/sync/group.role.service_provider-insider_root.yml
config/sync/group.role.service_provider-organization_ad.yml
config/sync/group.role.service_provider-outsider.yml
config/sync/group.type.organisation.yml
config/sync/group.type.service_provider.yml
config/sync/language/en/group.type.organisation.yml
config/sync/language/en/group.type.service_provider.yml
config/sync/language/en/views.view.group_nodes.yml
config/sync/language/sv/group.type.organisation.yml
config/sync/language/sv/group.type.service_provider.yml
config/sync/language/sv/views.view.group_nodes.yml
config/sync/views.view.group_nodes.yml
public/modules/custom/hel_tpm_group/hel_tpm_group.module

TP-1192 Group UX fixes

---

public/modules/custom/hel_tpm_group/hel_tpm_group.module

TP-1609 Fix cron error when groups have revisions

---

.github/workflows/ci.yml
.lando.yml
composer.json
composer.lock
docker/openshift/Dockerfile
public/modules/custom/hel_tpm_editorial/src/Plugin/Field/FieldWidget/HelTpmEditorialDateRecurCustomWidget.php
public/modules/custom/hel_tpm_service_stats/src/RevisionHistoryService.php
public/modules/custom/hel_tpm_user_expiry/src/Plugin/QueueWorker/UserExpirationNotification.php

lando rebuild && lando composer install && lando drush deploy
** PHP 8.3 **

TP-1543 Date row removal callbacks, updated date_recur modules, updated php to 8.3

---

config/sync/views.view.group_services.yml

TP-1615 Remove 'Service RTB publish' view from group services page

---

config/sync/language/en/views.view.group_content_ready_to_publish_revisions.yml
config/sync/language/sv/views.view.group_content_ready_to_publish_revisions.yml
config/sync/views.view.group_content_ready_to_publish_revisions.yml

TP-1617 Removed current state column from ready to publish lists

---

public/modules/custom/hel_tpm_group/src/Plugin/Group/RelationHandler/LeaveGroupAccessControl.php
public/modules/custom/hel_tpm_group/tests/src/Functional/LeaveGroupTest.php

Read the commit message for description.
_Testing removing group members_
_Testing removing group members_
_Testing removing content_

TP-1647 TP-1663 Fix altering access for leaving group

---

config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml

TP-1664 Allow anonymous users to view the age field

---

public/modules/custom/hel_tpm_group/hel_tpm_group.module

Hotfix TP-1676 Invalidate group membership cache when modifying subgroups

---

public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/GroupUserSelection.php
public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/ParentGroupSelection.php

Since PHP 8.0, when declaring a function, adding a required parameter after optional parameters is deprecated.
lando drush cr

TP-1692 Fix declaring optional parameter before required parameter

---

config/sync/views.view.group_content_ready_to_publish_revisions.yml
config/sync/views.view.service_rtb_publish_stats.yml

TP-1726 Fix permissions for rtp lists

---

public/modules/custom/hel_tpm_group/hel_tpm_group.module

TP-1747 Add group from relationship to empty municipality field

---

config/sync/views.view.cart.yml

TP-1727 Show only published services on favorite list

---

config/sync/language/en/views.view.group_nodes.yml
config/sync/language/en/views.view.group_responsibility_services.yml
config/sync/language/en/views.view.group_services.yml
config/sync/language/en/views.view.owner_and_responsible_updater.yml
config/sync/language/sv/views.view.group_nodes.yml
config/sync/language/sv/views.view.group_responsibility_services.yml
config/sync/language/sv/views.view.group_services.yml
config/sync/language/sv/views.view.owner_and_responsible_updater.yml
config/sync/views.view.group_content_ready_to_publish_revisions.yml
config/sync/views.view.group_nodes.yml
config/sync/views.view.group_responsibility_services.yml
config/sync/views.view.group_services.yml
config/sync/views.view.group_services_missing_updaters.yml
config/sync/views.view.owner_and_responsible_updater.yml
config/sync/views.view.ready_to_publish_for_organization_updater.yml
config/sync/views.view.service_publish_stats.yml
config/sync/views.view.service_rtb_publish_stats.yml

TP-1713 Show service IDs on lists

---

composer.json
composer.lock
config/sync/core.base_field_override.paragraph.content.created.yml
config/sync/core.base_field_override.paragraph.content.status.yml
config/sync/core.entity_form_display.node.basic_page.default.yml
config/sync/core.extension.yml
config/sync/field.field.paragraph.content_alt_editor.field_body_alt.yml
config/sync/field.field.paragraph.content_alt_editor.field_title.yml
config/sync/field.field.paragraph.link_card_row.field_linklist_card.yml
config/sync/field.field.paragraph.link_card_with_image.field_lift_image.yml
config/sync/field.field.paragraph.link_card_with_image.field_short_description.yml
config/sync/field.field.paragraph.link_card_with_image.field_single_link.yml
config/sync/field.field.paragraph.link_card_with_image.field_title.yml
config/sync/field.field.paragraph.quick_link_row.field_quick_link_row.yml
config/sync/field.field.paragraph.url_and_file.field_file.yml
config/sync/field.field.paragraph.url_and_file.field_link.yml
config/sync/language.content_settings.paragraph.content_alt_editor.yml
config/sync/language.content_settings.paragraph.link_card_row.yml
config/sync/language.content_settings.paragraph.link_card_with_image.yml
config/sync/language.content_settings.paragraph.url_and_file.yml

TP-1440 Basic page paragraph translations

---

public/modules/custom/hel_tpm_search/src/Plugin/better_exposed_filters/filter/SearchLanguageSelect.php
public/modules/custom/views_exposed_embed/src/Plugin/Field/FieldFormatter/ViewsExposedEmbedFieldDefaultFormatter.php

Since I couldn't reproduce this in local. This might need syncing of database from development environment

TP-1762 Fixed search language select warning, fixed no results showing when there's empty filters

---

public/modules/custom/hel_tpm_service_dates/hel_tpm_service_dates.module

TP-1807 Added language logic for field_time_additional_info field display logic

---

config/sync/core.entity_form_display.node.service.default.yml
public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldWidget/InlineEntityFormComplexNoConfirmWidget.php

TP-1879 Removed entity removal link from contact fields in translations

---

public/modules/custom/hel_tpm_service_stats/hel_tpm_service_stats.module
public/modules/custom/hel_tpm_service_stats/hel_tpm_service_stats.services.yml
public/modules/custom/hel_tpm_service_stats/src/HelTpmServiceStatsCron.php
public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/ServiceRowGroupField.php
public/modules/custom/hel_tpm_service_stats/src/Plugin/QueueWorker/DaysSinceLastStateChangeUpdater.php
public/modules/custom/hel_tpm_service_stats/src/RevisionHistoryService.php
public/modules/custom/service_manual_workflow/service_manual_workflow.module

TP-1862 Fixed last state change calculation bug for views listing

---

public/modules/custom/hel_tpm_editorial/src/Plugin/views/field/ServiceHasUnpublishedChanges.php

Added null check when fetching latesttranslationaffected revision.

---

config/sync/views.view.group_services_missing_updaters.yml
public/themes/custom/palvelumanuaali/components/05-pages/search/search-page-filters.js
translations/fi-interface-translations.po
translations/sv-interface-translations.po

TP-1923 Added default translation filter to services missing updaters view
