config/sync/context.context.front_page_content_producer.yml
config/sync/context.context.front_page_users.yml
config/sync/views.view.services.yml

drush cim
1. You should see one of two blocks on the front page depending on if you're logged in as a content producer or not. Other users see a block without the edit date and publish status, content producers see also those.

TP-110: New services block to front page

---

composer.json
composer.lock
public/sites/default/settings.platformsh.php

Configured platform.sh elastic search

---

config/sync/core.entity_view_display.message.1st_user_account_expiry_reminder.mail_body.yml
config/sync/core.entity_view_display.message.1st_user_account_expiry_reminder.mail_subject.yml
config/sync/core.entity_view_display.message.2nd_user_account_expiry_reminder.mail_body.yml
config/sync/core.entity_view_display.message.2nd_user_account_expiry_reminder.mail_subject.yml
config/sync/core.extension.yml
config/sync/language/fi/message.template.1st_user_account_expiry_reminder.yml
config/sync/language/fi/message.template.2nd_user_account_expiry_reminder.yml
config/sync/message.template.1st_user_account_expiry_reminder.yml
config/sync/message.template.2nd_user_account_expiry_reminder.yml
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.info.yml
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module

TP-153: User expiry messages and module

---

config/sync/core.extension.yml
public/modules/custom/hel_tpm_tracking/hel_tpm_tracking.info.yml
public/modules/custom/hel_tpm_tracking/hel_tpm_tracking.module
public/sites/default/settings.platformsh.php

Tp 164 matomo

---

composer.json
composer.lock
config/sync/context.context.services.yml
config/sync/core.entity_form_display.notification_message.service_notification.default.yml
config/sync/core.entity_view_display.message.1d_notification_expiry_reminder.mail_body.yml
config/sync/core.entity_view_display.message.1d_notification_expiry_reminder.mail_subject.yml
config/sync/core.entity_view_display.message.7d_notification_expiry_reminder.mail_body.yml
config/sync/core.entity_view_display.message.7d_notification_expiry_reminder.mail_subject.yml
config/sync/core.entity_view_display.notification_message.service_notification.default.yml
config/sync/core.extension.yml
config/sync/field.field.notification_message.service_notification.field_message_level.yml
config/sync/field.field.notification_message.service_notification.field_services.yml
config/sync/field.storage.notification_message.field_message_level.yml
config/sync/field.storage.notification_message.field_services.yml
config/sync/language/en/notification_message.type.global.yml
config/sync/language/fi/message.template.1d_notification_expiry_reminder.yml
config/sync/language/fi/message.template.7d_notification_expiry_reminder.yml
config/sync/language/sv/notification_message.type.global.yml
config/sync/message.template.1d_notification_expiry_reminder.yml
config/sync/message.template.7d_notification_expiry_reminder.yml
config/sync/notification_message.type.global.yml
config/sync/notification_message.type.service_notification.yml
config/sync/views.view.notifications.yml
public/modules/custom/hel_tpm_editorial/hel_tpm_editorial.info.yml
public/modules/custom/hel_tpm_editorial/hel_tpm_editorial.module
public/modules/custom/hel_tpm_editorial/src/Plugin/Validation/Constraint/NotificationMessageExpiryConstraint.php
public/modules/custom/hel_tpm_editorial/src/Plugin/Validation/Constraint/NotificationMessageExpiryConstraintValidator.php
public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.module

composer install; drush cim; drush cr

TP-162: Notification messages for services

---

config/sync/user.role.admin.yml

TP-162: Fix permissions for notification messages

---

config/sync/user.role.admin.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml

Fix permissions

---

public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.module

Removed required from search api fulltext element

---

config/sync/core.entity_form_display.node.service.default.yml
config/sync/core.entity_form_display.node.service_location.default.yml
config/sync/core.entity_view_display.node.service_location.card_lift.yml
config/sync/core.entity_view_display.node.service_location.default.yml
config/sync/core.entity_view_display.node.service_location.teaser.yml
config/sync/field.field.node.service_location.field_accessibility_details.yml
config/sync/field.storage.node.field_accessibility_details.yml

TP-160: Add accessibility details to service location

---

config/sync/core.entity_form_display.group.organisation.default.yml
config/sync/core.entity_form_display.group_content.group_content_type_c7845b3bab623.default.yml
config/sync/core.entity_view_display.group.organisation.default.yml
config/sync/core.entity_view_display.group_content.group_content_type_c7845b3bab623.default.yml
config/sync/field.field.group.organisation.field_service_owner.yml
config/sync/field.field.group_content.group_content_type_c7845b3bab623.field_service_owner.yml
config/sync/field.storage.group.field_service_owner.yml
config/sync/field.storage.group_content.field_service_owner.yml
config/sync/group.content_type.group_content_type_c7845b3bab623.yml

TP-189: Add a owner field to group services

---

public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

Fixed history suggestions

---

config/sync/core.entity_form_display.node.service.default.yml

Use select2 for the accessibility selection

---

azure-pipelines-devtest.yml
azure-pipelines-stageprod.yml

azure pipelines files

---

config/sync/views.view.service_search.yml

Exposed full text search field

---

public/sites/default/settings.php

PLATTA-3839: Use correct way to determine the Platta environment

---

config/sync/core.entity_view_display.node.service.internal.yml

Fixed missing fields

---

config/sync/core.entity_view_display.node.service.default.yml
config/sync/core.entity_view_display.node.service.internal.yml
config/sync/core.menu.static_menu_link_overrides.yml
config/sync/flag_lists.flag_for_list.lista.yml
config/sync/system.site.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.module
public/themes/custom/palvelumanuaali/components/02-molecules/menus/main-menu/main-menu-item.twig

Fixed a couple of bugs

---

config/sync/system.site.yml

Added default frontpage back to /

---

.platform/services.yaml

Reduced mysqldb size

---

config/sync/block.block.palvelumanuaali_local_tasks.yml
config/sync/context.context.sitewide.yml
config/sync/system.site.yml

Fixed context_id block notice

---

public/sites/default/settings.openshift.php

TP-302: Missing option for ES authentication

---

docker/openshift/docker-entrypoint.sh

TP-302: Try adding the CA certificate for ES

---

public/themes/custom/palvelumanuaali/components/03-organisms/site/site-sidebar/_site-sidebar-branding.twig

Changed front page link to support language

---

composer.lock
config/sync/core.extension.yml
docker/openshift/Dockerfile

Entity print security update

---

config/sync/core.entity_form_display.node.service.default.yml

Added 120 character limit to service node title

---

composer.json
composer.lock

Removed printable from composer and updated dompdf/dompdf package

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.service.default.yml
config/sync/core.entity_view_display.node.service.card_lift.yml
config/sync/core.entity_view_display.node.service.default.yml
config/sync/core.entity_view_display.node.service.internal.yml
config/sync/core.entity_view_display.node.service.teaser.yml
config/sync/core.entity_view_display.node.service.view_card_lift.yml
config/sync/core.extension.yml
config/sync/field.field.node.service.field_service_producer.yml
config/sync/field.storage.node.field_service_producer.yml

TP-334: Add fields to manage service group links on node form

---

config/sync/views.view.group_services.yml

Updated group services view

---

public/sites/default/settings.openshift.php

TP-359: Sentinel configuration instead for Redis

---

public/sites/default/settings.openshift.php

TP-359: Third time's the charm, I hope... Fixed Redis Sentinel config

---

public/modules/custom/hel_tpm_group/src/EventSubscriber/HelTpmGroupSubscriber.php

Fixed user role calculation

---

config/sync/core.entity_form_display.node.service.default.yml
config/sync/field.field.node.service.field_statements.yml
config/sync/field.storage.node.field_statements.yml

Added proper value for field statements no option and made the field

---

config/sync/migrate_plus.migration.organisation_import.yml
config/sync/migrate_plus.migration.service_groupcontent.yml

TP-358: Group content migration

---

config/sync/migrate_plus.migration.organisation_import.yml
config/sync/migrate_plus.migration.service_groupcontent.yml
config/sync/migrate_plus.migration.service_wp_import.yml
run_migration.sh

TP-358: Fix migration paths and add migration script

---

public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMURLFileParagraph.php
run_migration.sh

TP-358: Better migration run script

---

config/sync/migrate_plus.migration.service_groupcontent.yml
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMServicePriceParagraph.php
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMServiceTimeLocationParagraph.php

TP-358: Fix some more notices showing up only on Platta

---

composer.json
composer.lock
config/sync/core.extension.yml

Installed node_edit_protection

---

public/themes/custom/palvelumanuaali/templates/content/node--landing-page--full.html.twig

Changed email for landing page greeting message

---

config/sync/system.site.yml

Changed frontpage to alias

---

config/sync/core.entity_form_display.node.service.default.yml

Changed obligatorynes to radios

---

config/sync/system.site.yml

Fixes regression happened in another branch

Fixed frontpage alias

---

config/sync/language/en/views.view.solr_service_search.yml
config/sync/language/sv/views.view.solr_service_search.yml
config/sync/views.view.solr_service_search.yml

Added translations for search button

---

docker/solr/Dockerfile
docker/solr/start.sh

SOLR Dockerfile and entrypoint script

---

public/sites/default/settings.openshift.php

Added solr core configs for openshift

---

public/themes/custom/palvelumanuaali/templates/content/node--landing-page--full.html.twig

Removed email from greeting text

---

public/modules/custom/hel_tpm_general/src/Form/BulkGroupInvitationRoles.php

Fixed bulk group invitation

---

public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

lando drush cr  and force refresh browser window.

Changed history limit to 5 and reafctored javascript a bit

---

config/sync/language.types.yml
config/sync/views.view.cart.yml
config/sync/views.view.recently_read_content.yml
config/sync/views.view.services.yml
config/sync/views.view.solr_service_search.yml
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

Added content language negotiation and fixed language switcher

---

public/modules/custom/hel_tpm_search/src/EventSubscriber/SearchBoostSubscriber.php

Fixed elastic search subscriber error

---

config/sync/context.context.group_links.yml

Removed services block from context

---

config/sync/core.entity_form_display.user.user.default.yml

Hide timezone selection from user profile

---

config/sync/search_api.index.service_search_solr_index.yml
config/sync/search_api_autocomplete.search.solr_service_search.yml
public/modules/custom/hel_tpm_search_autosuggest/templates/hel-tpm-search-autocomplete.html.twig

Swapped autocomplete order and configured better suggester

---

config/sync/core.entity_form_display.node.basic_page.default.yml
config/sync/pathauto.pattern.content.yml

Add patterns and form element for path aliases

---

config/sync/migrate_plus.migration.service_groupcontent.yml
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/ParagraphBase.php
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMHandleObligatoryness.php
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMServiceTimeLocationParagraph.php
public/modules/custom/hel_tpm_migrate_tools/src/Plugin/migrate/process/TPMTargetGroupParagraph.php

Migration fixes

---

public/modules/custom/hel_tpm_search_autosuggest/templates/hel-tpm-search-autocomplete.html.twig

Moved autocomplete search suggestions to top

---

config/sync/user.role.admin.yml

Added nodeaccess permissions for admin role

---

config/sync/field.storage.node.field_obligatoryness.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.install

Combiness first two choices into one.

TP-644 Change choices of obligatoryness field

---

public/themes/custom/palvelumanuaali/components/05-pages/content-types/service.twig

TP-625 add link for the archive

---

config/sync/field.storage.node.field_statements.yml

Updated statements value descriptions

---

public/sites/default/settings.openshift.php

Changed environment variable configs

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install

Fixed spacing

---

config/sync/field.field.paragraph.target_group.field_description.yml
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

Added error class for textarea wrapper

---

config/sync/smtp.settings.yml

Added proper from mail and name for mail sending

---

config/sync/core.entity_form_display.paragraph.service_time_and_place.default.yml

Changed service time and place widget to paragraph legacy

---

docker/openshift/Dockerfile

Changed docker version

---

scripts/location-import.php

Changed json path

---

public/modules/custom/hel_tpm_forms/js/hel_tpm_forms.js

Removed next button from last form page

---

public/themes/custom/palvelumanuaali/templates/layout/html.html.twig

Lando drush cr
fixes favicon pathing

TP-710 adjust favicon pathing

---

config/sync/core.entity_form_display.node.service.default.yml
config/sync/core.entity_form_display.paragraph.content.default.yml
config/sync/core.entity_form_display.paragraph.municipality_guide.default.yml
config/sync/core.entity_form_display.paragraph.quick_link.default.yml
config/sync/core.entity_form_display.paragraph.service_price.default.yml

TP-676 Field char limit

---

config/sync/field.storage.paragraph.field_municipality.yml

Changed municipality to single value field

---

config/sync/field.field.node.service.field_responsible_updatee.yml

Changed field_responsible_updatee to non-required field

---

config/sync/user.settings.yml

Disabled visitor account creation

---

public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/GroupUserSelection.php

Added permission check for buildqentityquery so that administrators can list all users

---

composer.lock

Installed SA-CORE-2023-002

---

config/sync/core.entity_form_display.node.service.default.yml

Changed municipality fields to not have default value when creating service

---

config/sync/field.field.node.service.field_related_archive.yml

Removed default value from related archive field

---

config/sync/core.entity_form_display.node.service.default.yml

Moved municipality instruction to proper place

---

config/sync/views.view.cart.yml
public/themes/custom/palvelumanuaali/palvelumanuaali.theme
public/themes/custom/palvelumanuaali/templates/content/node--view-card-lift.html.twig

TP-749 removed published requirement from favorites view

---

config/sync/views.view.group_subgroup_services.yml
public/modules/custom/hel_tpm_forms/js/hel_tpm_forms.js

TP-766 add responsible updatee column to subgroup services view

---

public/themes/custom/palvelumanuaali/templates/fields/field--node--field-service-suits-job-search--service.html.twig

Fixed field service suits job search display

---

config/sync/core.entity_view_display.node.service_location.default.yml
public/modules/custom/hel_tpm_forms/hel_tpm_forms.install
public/modules/custom/hel_tpm_forms/hel_tpm_forms.module

Added automatic service location title generation, removed duplicate address and added update hook to update existing service location titles

---

public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/GroupUserSelection.php

Added ability to admins override user list

---

config/sync/field.storage.paragraph.field_municipality.yml

TP-782 Change choice type of municipalities

---

config/sync/core.entity_form_display.node.service.default.yml
config/sync/core.entity_form_display.paragraph.content.default.yml
config/sync/core.entity_form_display.paragraph.content_link_file.default.yml
config/sync/core.entity_form_display.paragraph.content_link_file_guide.default.yml
config/sync/core.entity_form_display.paragraph.long_text_field_with_toolbar.default.yml
config/sync/core.entity_form_display.paragraph.municipality_guide.default.yml
config/sync/core.entity_form_display.paragraph.quick_link.default.yml
config/sync/core.entity_form_display.paragraph.service_price.default.yml
config/sync/core.entity_form_display.paragraph.target_group.default.yml
config/sync/field.storage.paragraph.field_municipality.yml

TP-777 remove max char limit from various fields

---

config/sync/views.view.group_subgroup_services.yml

Added edit link for subgroup services

---

config/sync/group.role.organisation-editor.yml

Added organization editor permission to use publish state

---

config/sync/user.role.specialist_editor.yml
config/sync/views.view.group_subgroup_services.yml

Added specialist editor permission to see emails

---

config/sync/views.view.cart.yml

Disabled sql rewriting for cart view

---

config/sync/views.view.group_services.yml
config/sync/views.view.group_subgroup_services.yml

TP-773 Add correct filter values for service views

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.libraries.yml

Changed hel_tpm_forms version

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.libraries.yml
public/modules/custom/hel_tpm_forms/hel_tpm_forms.module
public/modules/custom/hel_tpm_forms/js/hel_tpm_forms_custom_submit.js
public/modules/custom/service_manual_workflow/service_manual_workflow.module

Created custom status submit button

---

config/sync/core.entity_form_display.node.service.default.yml

Changed field widget to paragraph legacy

---

config/sync/views.view.group_subgroup_services.yml

Fixed pagination

---

config/sync/core.entity_form_display.node.service.default.yml
config/sync/field.field.node.service.field_obligatoryness_freetext.yml
config/sync/field.field.node.service.field_statements_unemployment.yml
config/sync/field.field.paragraph.long_text_field_with_toolbar.field_description.yml

Changed obligatoryness, unembloyment statement and description paragraph

---

config/sync/block.block.views_block__group_produced_services_block_1.yml
config/sync/language/fi/block.block.views_block__group_produced_services_block_1.yml
config/sync/views.view.group_produced_services.yml

Created views listing services produced by group

---

config/sync/workflows.workflow.service_moderation.yml

Removed temoprarily archived and on hold statuses. Added abilityt to move service from outdated to draft.

---

config/sync/group.content_type.group_content_type_3652c4b169b23.yml

Added editor inheritance permission

---

public/modules/custom/hel_tpm_group_invite/src/Form/BulkGroupInvitationCustomConfirm.php

Bypassed invitation acceptance process and added user to group immediately 

---

config/sync/system.site.yml

TP-886 change site name

---

public/modules/custom/hel_tpm_group/src/EventSubscriber/HelTpmGroupRouteSubscriber.php

Added administer users permission to group.add_member route

---

config/sync/core.entity_form_display.node.service.default.yml

Added default value back to time and date element

---

config/sync/field.storage.paragraph.field_municipality.yml

TP-878 Changed municipality to allow only one value

---

config/sync/user.role.editor.yml

TP-871 hide toolbar from editors

---

config/sync/block.block.views_block__group_produced_services_block_1.yml
config/sync/views.view.group_produced_services.yml
public/modules/custom/hel_tpm_group/src/Plugin/views/argument_default/GroupIdFromGroup.php

Created groupidfromgroup default argument and added to produced service view

---

config/sync/workflows.workflow.service_moderation.yml

TP_880 Allowed ready to publish transition from published and outdated statuses

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/field.field.node.service.field_instructions_markup.yml
config/sync/language/en/field.field.node.service.field_instructions_markup.yml
config/sync/language/sv/field.field.node.service.field_instructions_markup.yml

Installed advanced editor link and added target blank for instructions link

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.module
public/modules/custom/hel_tpm_forms/js/hel_tpm_forms_custom_submit.js

TP-891 fixed problem with select fields when changin user roles

---

public/modules/custom/hel_tpm_group_invite/src/Form/BulkGroupInvitationCustom.php
public/modules/custom/hel_tpm_group_invite/tests/Functional/GroupBulkInviteTest.php

TP-889 Added role selection as mandatory and updated test

---

.lando.yml
public/sites/default/settings.php

lando rebuild && lando drush cr

TP-776 added support to set private file path from environment variable

---

config/sync/core.entity_form_display.paragraph.target_group.default.yml
config/sync/core.entity_view_display.paragraph.target_group.default.yml
config/sync/field.field.paragraph.target_group.field_target_group_municipality.yml
config/sync/field.storage.paragraph.field_target_group_municipality.yml
config/sync/group.content_type.group_content_type_c7845b3bab623.yml
config/sync/language/en/field.field.paragraph.target_group.field_target_group_municipality.yml
config/sync/language/sv/field.field.paragraph.target_group.field_target_group_municipality.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.install

Created target group municipality and migrated field data

---

config/sync/group.role.service_provider-outsider.yml

TP-891 Added outsider permission to view all sub groups

---

config/sync/user.role.admin.yml
config/sync/user.role.editor.yml
config/sync/user.role.specialist_editor.yml
config/sync/views.view.users_by_group_entity_reference.yml

Added permission to editors to use entity browser and dropzone

---

public/modules/custom/hel_tpm_forms/js/hel_tpm_forms_service_form_pagination.js

TP-888 Added scroll top when switching pages on service form

---

composer.json
composer.lock
patches/moderation-state-orderby-mysql-error.patch

Hotfix Patched orderby error from moderation state

---

config/sync/block.block.views_block__group_produced_services_block_1.yml
config/sync/filter.format.filtered_html.yml
config/sync/group.role.service_provider-organization_ad.yml
config/sync/views.view.admin_services.yml
config/sync/views.view.group_nodes.yml
config/sync/views.view.group_services.yml
config/sync/views.view.owner_and_responsible_updatee.yml
public/modules/custom/hel_tpm_editorial/hel_tpm_editorial.module
public/modules/custom/hel_tpm_editorial/src/Plugin/views/field/ServiceHasUnpublishedChanges.php
translations/fi-interface-translations.po

TP-897 added service has changes field to service list views

---

config/sync/language/en/core.entity_view_display.node.service.default.yml
config/sync/language/sv/core.entity_view_display.node.service.default.yml
config/sync/views.view.group_services.yml

Added edit link for service list

---

config/sync/views.view.group_subgroup_services.yml
public/modules/custom/hel_tpm_editorial/hel_tpm_editorial.module
public/modules/custom/hel_tpm_editorial/src/Plugin/views/field/ServiceHasUnpublishedChanges.php
public/modules/custom/hel_tpm_editorial/templates/service_has_changes_field.html.twig

TP-896 added moderation state for "has changes" views field

---

public/modules/custom/hel_tpm_tooltips/js/tooltips.js

Removed unnecessary function argument

---

config/sync/views.view.group_responsibility_services.yml

TP-921 changed reponsible services subgroup to "palvelun järjestäjä"

---

config/sync/views.view.admin_services.yml

TP-942 added responsible municipality field filter for admin services

---

public/themes/custom/palvelumanuaali/js/matomo.js
public/themes/custom/palvelumanuaali/palvelumanuaali.libraries.yml

TP-658 added matomo to theme

---

config/sync/field.field.node.service.field_service_provider_updatee.yml

TP-922 set service provider updatee as required

---

config/sync/views.view.group_responsibility_services.yml

TP-936 added current group filter for responsibility services view

---

config/sync/views.view.group_responsibility_services.yml

TP-954 removed author and added language column for responsibility services

---

config/sync/language/en/views.view.admin_groups.yml
config/sync/language/sv/views.view.admin_groups.yml
config/sync/views.view.admin_groups.yml

`drush cim`
`drush cr`
* Login and go to `/admin/group`.
* Check that you can sort the table by name and group type,
* Check that you can filter the table by group name.

TP-946 Add name filter and sorting options

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/user.role.admin.yml
config/sync/views.view.groups_export.yml
config/sync/views.view.services_export.yml
config/sync/views.view.users_export.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.permissions.yml

TP-940: User/group/service excel exports

---

config/sync/views.view.admin_services.yml

TP-972 Refactored admin services view

---

config/sync/block.block.hel_print_pdf_block.yml
config/sync/block.block.palvelumanuaali_messages.yml
config/sync/block.block.views_block__cart_favorites_block.yml
config/sync/block.block.views_block__group_produced_services_block_1.yml
config/sync/block.block.views_block__group_title_view_block_1.yml
config/sync/block.block.views_block__ready_to_publish_for_organization_updatee_block_1.yml
config/sync/block.block.views_block__recently_read_content_recently_viewed_service_table.yml
config/sync/block.block.views_block__services_last_updated_table_block.yml
config/sync/block.block.views_block_notifications_block_1.yml
config/sync/language/en/views.view.ready_to_publish_for_organization_updatee.yml
config/sync/language/sv/views.view.ready_to_publish_for_organization_updatee.yml
config/sync/views.view.ready_to_publish_for_organization_updatee.yml

`Lando drush deploy `
Creates view to /hallinta-ja-ylläpito that shows ready to publish content

TP-930 Responsible updatee ready to publish view

---

config/sync/block.block.hel_print_pdf_block.yml
config/sync/block.block.local_actions_block.yml
config/sync/block.block.palvelumanuaali_local_tasks.yml
config/sync/block.block.palvelumanuaali_messages.yml
config/sync/block.block.palvelumanuaali_page_title.yml
config/sync/block.block.system_breadcrumb_bloc.yml
config/sync/block.block.views_block__group_title_view_block_1.yml
config/sync/block.block.views_block__organizatio_with_ready_to_publish_content_block_1.yml
config/sync/core.entity_view_display.group.organisation.token.yml
config/sync/views.view.group_content_ready_to_publish.yml
config/sync/views.view.organizatio_with_ready_to_publish_content.yml
public/themes/custom/palvelumanuaali/templates/content/group--token.html.twig
public/themes/custom/palvelumanuaali/templates/views/eva-display-entity-view.html.twig

`Lando drush deploy`
Creates a view to /hallinta-ja-yllapito page for organisation groups organisation admins
that display ready to publish content from said organisation and its' subgroups.

TP-931 create view ready to publish content for organisation admins

---

composer.lock

SA-CONTRIB-2023-045

---

config/sync/language/en/views.view.group_services.yml
config/sync/language/sv/views.view.group_services.yml
config/sync/views.view.group_members.yml
config/sync/views.view.group_produced_services.yml
config/sync/views.view.group_responsibility_services.yml
config/sync/views.view.group_services.yml
config/sync/views.view.owner_and_responsible_updatee.yml

Login & check that the following views have column titles in finnish

TP-968: Column translations from prod

---

public/themes/custom/palvelumanuaali/palvelumanuaali.info.yml
public/themes/custom/palvelumanuaali/palvelumanuaali.theme
public/themes/custom/palvelumanuaali/templates/layout/html.html.twig

drush cr
Check the logs that there are no more warnings:

TP-1017: Fix some issues catch from log

---

config/sync/eu_cookie_compliance.settings.yml

TP-184 Allow cookie for closed notifications

---

composer.lock

Resolves SA-CORE-2023-006.
drush deploy

Update Drupal to version 9.5.11

---

config/sync/language/en/views.view.solr_service_search.yml
config/sync/language/sv/views.view.solr_service_search.yml
config/sync/views.view.solr_service_search.yml

TP-874 Use autosubmit with search filters

---

public/themes/custom/palvelumanuaali/palvelumanuaali.theme
public/themes/custom/palvelumanuaali/templates/content/node--view-card-lift.html.twig

TP-734 added organizing group for service view card liftups

---

config/sync/views.view.solr_service_search.yml

TP-517 Added municipality residence support does not matter support for search

---

composer.lock

SA-CONTRIB-2023-048

---

composer.json
composer.lock

Installed maillogin security update

---

config/sync/group.role.organisation-administrator.yml
config/sync/group.role.service_provider-editor.yml
config/sync/group.role.service_provider-group_admin.yml
config/sync/group.role.service_provider-organization_ad.yml
config/sync/user.role.admin.yml
config/sync/user.role.authenticated.yml
config/sync/user.role.editor.yml

TP-1030 disabled archival prossibility from group admins

---

public/modules/custom/hel_tpm_group/tests/src/Kernel/HelTpmGroupSubscriberTest.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/SiteWideGroupRoleTest.php
public/modules/custom/service_manual_workflow/src/ServiceNotificationTrait.php

TP-1039 changed getGroupContent method calls to getGroupRelationship

---

composer.json
composer.lock
config/sync/field.field.node.service.field_service_language.yml
patches/require_on_publish-paragraph-fix-for-ready_to_publish.patch

drush cim
drush cr
Check that for the following fields:
- Service language (1st tab) 
- Municipality of residence (1st tab)
- Description of service target group (1st tab)
- Method of organizing (3rd tab -> customer tab)
- Participation in the service (3rd tab -> customer tab)
...the following is true:

TP-1052 Required paragraph fields

---

composer.json
composer.lock
public/modules/custom/hel_tpm_group/src/CurrentGroup.php

TP-1116 Group views ajax error

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install

TP-1034 language field migration

---

public/themes/custom/palvelumanuaali/palvelumanuaali.theme

hotfix missing field preprocess

---

public/themes/custom/palvelumanuaali/palvelumanuaali.theme

Removed invisible character

---

public/modules/custom/hel_tpm_editorial/src/Plugin/Validation/Constraint/NotificationLimitConstraintValidator.php

Add missing accessCheck for notification validator

---

config/sync/smtp.settings.yml

Disabled auto tls.

---

public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldFormatter/MunicipalityFieldFormatter.php

Refactored municipality formatter

---

config/sync/core.entity_form_display.paragraph.target_group.default.yml
config/sync/core.entity_view_display.paragraph.target_group.default.yml

TP-974 Changed municipality selection widget to select2

---

public/sites/default/settings.openshift.php

TP-1121 Added proper environemen vars for varnish purger

---

public/modules/custom/service_manual_workflow/tests/Kernel/ContentGroupServiceTest.php

TP-1135 Added tests for ContentGroupService

---

public/modules/custom/hel_tpm_search/js/hel-tpm-search.multiselect-dropdown.js

TP-1186 Hotfix price filter multiselect

---

public/modules/custom/hel_tpm_search/js/hel-tpm-search.multiselect-dropdown.js
public/sites/default/settings.openshift.php

Hotfix for service search filters

---

public/modules/custom/hel_tpm_search/hel_tpm_search.libraries.yml

Updated dropdown_multiselect library version

---

config/sync/field.field.node.service.field_service_time_and_location.yml

`Drush cim`
Removes "required on publish on place and time" service element

TP-1195 Allow price and time field to no be filled when publishing

---

config/sync/field.field.node.service.field_instructions_markup.yml

TP-1201 Fix instrutions translation visibility

---

config/sync/search_api.index.service_search_solr_index.yml

TP-1197 Enabled hierarchical indexing for municipality

---

public/themes/custom/palvelumanuaali/templates/fields/field--node--field-service-set--service.html.twig

TP-1190 remove twig logic that adds and

---

public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

TP-1147 added 3 character limit for search autosuggestion

---

config/sync/core.entity_view_display.node.service.default.yml
public/modules/custom/hel_tpm_general/config/schema/hel_tpm_general.schema.yml
public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldFormatter/TimeAndPlaceFormatter.php

TP-1007 Hide time and place element when location is not selected.

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install

**Before** pulling the branch, edit some existing services:
(It might be good idea to export the testing db at this point if you need to run the deploy multiple times.)
Pull the changes from this branch and run `composer install` and `drush deploy`.

TP-1128 Fix issue with empty inner paragraph

---

composer.json
composer.lock

Updated Drupal core to version 10.1.8. The version is locked below 10.2 as it should be tested seperately.
drush deploy

TP-1245 Update core to version 10.1.8

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.module

TP-1230 Fix referenced user options

---

public/sites/default/settings.openshift.php

Added trusted_host_patterns

---

public/sites/default/settings.openshift.php

Moved trusted host setting

---

config/sync/eu_cookie_compliance.settings.yml

TP-1277 Update privacy policy version to 1.1.0

---

public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.libraries.yml

Hotfix updated search autosuggest library version

---

config/sync/message.settings.yml
public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.install
public/modules/custom/hel_tpm_update_reminder/hel_tpm_update_reminder.module
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module
public/modules/custom/hel_tpm_user_expiry/src/Plugin/QueueWorker/UserExpirationNotification.php
public/modules/custom/hel_tpm_user_expiry/tests/src/Kernel/UserExpirationTest.php

TP-1284 Fixed user expiry mail sending, updated tests, added removal of over 6 month old messages 

---

composer.lock

Installed security updates

---

config/sync/views.view.groups_without_admins.yml

Added groups without admins list to menu tab

---

config/sync/views.view.cart.yml

Enabled favorites page

---

config/sync/views.view.group_services_missing_updatee.yml

TP-1318 Changed no results behavior for services missing updatees list

---

composer.lock
public/modules/custom/hel_tpm_general/drush.services.yml
public/modules/custom/hel_tpm_general/src/Drush/Commands/sql/UsernameSanitizeCommands.php

TP-1122 Updated drush for sql:sanitize --ignored-roles compatiblity

---

config/sync/search_api.index.service_search_solr_index.yml

TP-1315 Enabled solr to sync contents in real time.

---

public/modules/custom/hel_tpm_search_autosuggest/css/hel-tpm-search-autosuggest.css
public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.libraries.yml
public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

TP-1366 Fixed search autocomplete not working on keyup

---

config/sync/views.view.search_municipality_services.yml

`Lando drush deploy`
Filters taxonomy views by user UI lang.

TP-1353 add filtering for current ui language

---

config/sync/field.field.node.service.field_service_languages.yml
config/sync/field.field.paragraph.service_language.field_language.yml

TP-1337 Changed language field as required on publish

---

config/sync/eu_cookie_compliance.settings.yml
config/sync/language/en/eu_cookie_compliance.settings.yml
config/sync/language/sv/eu_cookie_compliance.settings.yml

Texts can be found from TP-1358 

TP-1358 Updated cookie banner texts

---

public/modules/custom/hel_tpm_group/tests/modules/hel_tpm_group_test_views/config/install/views.view.test_moderation_state_excluding_archived.yml
public/modules/custom/hel_tpm_group/tests/modules/hel_tpm_group_test_views/hel_tpm_group_test_views.info.yml
public/modules/custom/hel_tpm_group/tests/src/Kernel/GroupRelationshipFormAccessTest.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/GroupUserSelectionReferenceTest.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/ParentGroupSelectionReferenceTest.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/ViewsModerationStateExcludeArchivedTest.php

Added more tests for the hel_tpm_group module.

TP-1061 hel_tpm_group tests

---

composer.json
composer.lock

Reverted bef to 6.0.3 due to autosubmission issues

---

public/modules/custom/hel_tpm_search_autosuggest/css/hel-tpm-search-autosuggest.css

TP-1142 fix adjusted search dropdown border

---

public/modules/custom/hel_tpm_forms/hel_tpm_forms.module

Fixed service execution and attendace field validations.

---

config/sync/views.view.group_responsibility_services.yml

TP-1413 change responsibility services view header sticky

---

phpunit.xml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/core.entity_form_display.paragraph.long_text_field_with_toolbar.default.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/core.entity_form_display.paragraph.service_language.default.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.node.service.field_attendance.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.node.service.field_description.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.node.service.field_service_execution.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.node.service.field_service_languages.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.paragraph.long_text_field_with_toolbar.field_description.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.paragraph.service_language.field_language.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.field.paragraph.service_language.field_level.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.node.field_attendance.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.node.field_description.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.node.field_service_execution.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.node.field_service_languages.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.paragraph.field_language.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/field.storage.paragraph.field_level.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/paragraphs.paragraphs_type.long_text_field_with_toolbar.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/paragraphs.paragraphs_type.service_language.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/taxonomy.vocabulary.language_level.yml
public/modules/custom/hel_tpm_forms/tests/modules/hel_tpm_forms_config_test/config/install/taxonomy.vocabulary.service_languages.yml
public/modules/custom/hel_tpm_forms/tests/src/Functional/ServiceEditFormTest.php
public/modules/custom/hel_tpm_forms/tests/src/Functional/ServiceLocationEditFormTest.php
public/modules/custom/hel_tpm_forms/tests/src/Kernel/ServiceLocationTitleTest.php

TP-1439 hel_tpm_forms test updates

---

composer.json
composer.lock
public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.libraries.yml
public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

TP-1434 Patched issue making content untranslatable

---

config/sync/language/en/views.view.solr_service_search.yml
public/modules/custom/hel_tpm_search/src/Plugin/better_exposed_filters/filter/DropdownMultiselect.php

TP-1450 Fixed service set filter transaltions, added translations for service language label and service is chargeable filters

---

public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldWidget/OptgroupTermSelect2Widget.php

TP-1484 Added value re-keying for getselectedoptions

---

public/modules/custom/hel_tpm_search/js/hel-tpm-search.taxonomy-hierarchy-select.js
translations/fi-interface-translations.po
translations/sv-interface-translations.po

lando drush cr
lando drush -y locale:import fi ../translations/fi-interface-translations.po &&
lando drush -y locale:import sv ../translations/sv-interface-translations.po

TP-1422 Added show all selection to municipality first level selection and added translations.

---

public/modules/custom/hel_tpm_search/src/Plugin/better_exposed_filters/filter/DropdownMultiselect.php

Apparently merging https://github.com/City-of-Helsinki/drupal-helfi-tyollisyyspalvelut-manuaali/pull/742 broke changes in https://github.com/City-of-Helsinki/drupal-helfi-tyollisyyspalvelut-manuaali/pull/741.
drush deploy

TP-1435 Fix preserving parent term order

---

composer.json
composer.lock
config/sync/block_class.settings.yml

drush deploy
Check that everything seems to work, e.g.:

TP-1490 Module updates

---

composer.json
composer.lock
patches/ginvite-3.0.0-rc1-pre-core-10.3-config-fix.patch
public/modules/custom/hel_tpm_group_invite/src/Form/BulkGroupInvitationCustom.php
public/modules/custom/hel_tpm_group_invite/src/Form/BulkGroupInvitationCustomConfirm.php
public/modules/custom/hel_tpm_group_invite/tests/Functional/GroupBulkInviteTest.php

 TP-1494 Update ginvite to version 3.0.0-rc1

---

composer.json
composer.lock

TP-1493 Fix editing non-translatable fields

---

config/sync/language/en/views.view.solr_service_search.yml
config/sync/palvelumanuaali.settings.yml
public/themes/custom/palvelumanuaali/templates/layout/html.html.twig

TP-867 Fixed favicon on chrome

---

config/sync/core.entity_form_display.node.service.default.yml
public/modules/custom/hel_tpm_contact_info/src/ContactInfoListBuilder.php
public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldWidget/InlineEntityFormComplexMunicipalitySpecificWidget.php
public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldWidget/InlineEntityFormComplexNoConfirmWidget.php

TP-949 No confirmation on contacts removal

---

public/themes/custom/palvelumanuaali/templates/content/node--service--customer-view.html.twig

fix faulty comparison line

---

public/modules/custom/hel_tpm_url_shortener/src/Form/ShortenUrlLinkForm.php

Fixed short link creation ajax error

---

public/themes/custom/palvelumanuaali/templates/block/block--user-login-block.html.twig

TP-1557 replace the mobile login ledger close icon

---

composer.json
composer.lock
patches/block-class-array-merge-error.patch
patches/block-class-presave-string-to-array.patch

lando db-import older-db-dump.sql
lando drush en emulsify_tools && lando drush theme:install emulsify
lando drush cim -y

Added patches to prevent deploy block_class crash

---

public/modules/custom/hel_tpm_forms/js/hel_tpm_forms_custom_submit.js
public/modules/custom/service_manual_workflow/js/service-confirm-popup.js

Fixed service confirm popup

---

config/sync/views.view.service_publish_stats.yml

TP-1561 Changed service publish stats column order

---

public/modules/custom/hel_tpm_editorial/src/Plugin/Field/FieldWidget/HelTpmEditorialDateRecurCustomWidget.php
translations/fi-interface-translations.po

TP-1562 Fixed start date validation

---

config/sync/entity_export_csv.entity_export_csv.service_publish_stats.yml
config/sync/entity_export_csv.settings.yml
public/modules/custom/hel_tpm_service_stats/src/Entity/ServicePublishedRow.php
public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/FieldType/DaysSinceStateChangeItem.php
public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/PublishIntervalField.php
public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/ServiceRowGroupField.php

TP-1512 Added groups to service publish stats export

---

config/sync/language/en/views.view.service_publish_stats.yml
config/sync/language/sv/views.view.service_publish_stats.yml
config/sync/views.view.service_publish_stats.yml

TP-1560 Created responsibility service publishing stats block

---

config/sync/views.view.service_publish_stats.yml

TP-1561 Changed responsible municipality publish stats columns

---

config/sync/views.view.service_publish_stats.yml

TP-1561 Reorderd date columns

---

public/modules/custom/hel_tpm_editorial/src/Plugin/Field/FieldWidget/HelTpmEditorialDateRecurCustomWidget.php

HotfixFixed error when saving service without service time

---

config/sync/views.view.group_responsibility_services.yml
config/sync/views.view.service_rtb_publish_stats.yml

TP-1588 Created responsibility services rtb services view

---

composer.lock
config/sync/views.view.owner_and_responsible_updatee.yml

TP-1507 Enabled ajax and auto submit for own responsibility services listing

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/views.view.admin_groups.yml
public/modules/custom/hel_tpm_group/src/Plugin/Action/CloseGroup.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/GroupCloseGroupTest.php
public/modules/custom/hel_tpm_group/tests/src/Kernel/GroupUserSelectionReferenceTest.php
public/modules/custom/hel_tpm_group/tests/src/Traits/GroupInitTrait.php

TP-1539 Created group archival action

---

composer.lock

TP-1620 Update Drupal core to version 10.3.10

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/menu_item_role_access.config.yml

TP-1603 Installed menu link role module

---

config/sync/views.view.services_export_revision.yml

Disabled batch export from service export

---

config/sync/language/en/views.view.user_admin_people.yml
config/sync/views.view.user_admin_people.yml

TP-1489 Modify users list date columns

---

composer.json

Removed cghooks from post install/update commands

---

config/sync/language/en/views.view.subgroups.yml
config/sync/views.view.subgroups.yml

TP-1630 TP-1628 Service provider remove relation

---

config/sync/views.view.solr_service_search.yml

TP-1644 Added inkoo, sipoo and kauniainen to municipality search filter

---

config/sync/views.view.group_responsibility_services.yml

TP-1627 Allowed only selectable languages for language filter

---

.sonarcloud.properties

TP-1427 Define source code and test code for SonarCloud

---

config/sync/core.entity_view_display.media.image.default.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml

TP-1664 Allow anonymous users to view the age field

---

public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/FieldWidget/DaysSinceLastStateChangeWidget.php

TP-1616 Fixed default value setting

---

public/themes/custom/palvelumanuaali/palvelumanuaali.libraries.yml

Added custom version for theme global libraries

---

public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/FieldWidget/DaysSinceLastStateChangeWidget.php
public/themes/custom/palvelumanuaali/palvelumanuaali.libraries.yml

Stage & Production varnish cache hotfix

---

composer.json
composer.lock
config/sync/diff.settings.yml
public/modules/custom/hel_tpm_editorial/src/Plugin/diff/Layout/ServiceEntityVisualInlineDiffLayout.php

TP-1610 Patched multiple revision list issues, created custom diff for services.

---

public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.install
public/modules/custom/hel_tpm_user_expiry/src/Anonymizer.php

TP-1680 Added force anonymization support to anonymizer, added new update hook to anonymize all blocked accounts changed more than 30 days ago

---

config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml

Added anonymous and authenticated users permission to see service list paragraphs

---

config/sync/field.field.node.basic_page.field_other_services.yml
config/sync/field.storage.node.field_other_services.yml
config/sync/views.view.published_services_selection.yml

TP-1671 Added views filter to field_other_services to prevent selecting other than published services

---

config/sync/views.view.group_content_ready_to_publish_revisions.yml
config/sync/views.view.group_responsibility_services.yml
config/sync/views.view.organizatio_with_ready_to_publish_content.yml

Changed rtp views cache to 1min

---

public/modules/custom/hel_tpm_editorial/src/Plugin/Field/FieldWidget/HelTpmEditorialDateRecurCustomWidget.php

TP-1691 Fixed validation when incomplete date is given

---

config/sync/pathauto.settings.yml

Removed dash removal from url alias

---

composer.json
composer.lock

SA-CORE-2025-001

---

composer.json
composer.lock

Installed SA-CORE-2025-001

---

composer.lock
public/modules/custom/hel_tpm_editorial/src/Plugin/views/field/ServiceHasUnpublishedChanges.php
public/modules/custom/hel_tpm_url_shortener/src/Form/ShortenerredirectForm.php
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

Fixed merge conflicts

---

public/modules/custom/hel_tpm_editorial/src/Plugin/views/field/ServiceHasUnpublishedChanges.php
public/modules/custom/hel_tpm_url_shortener/src/Form/ShortenerredirectForm.php
public/modules/custom/hel_tpm_user_expiry/hel_tpm_user_expiry.module
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

Removed superfluous characters

---

config/sync/user.role.admin.yml
config/sync/workflows.workflow.service_moderation.yml

TP-1675 Created new archived to draft transition and allowed it only for admins

---

public/themes/custom/palvelumanuaali/templates/date-recur-basic-formatter.html.twig

Brought back date-recur-basic-formatter template

---

public/modules/custom/hel_tpm_group/src/GroupSelectionTrait.php
public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/GroupUserSelection.php
public/modules/custom/hel_tpm_group/src/Plugin/EntityReferenceSelection/ParentGroupSelection.php

Fix responsible municipality group selection

---

config/sync/field.field.node.service.field_other_services.yml

TP-1671 Added published services filter for other service field

---

config/sync/views.view.group_content_ready_to_publish_revisions.yml
config/sync/views.view.service_rtb_publish_stats.yml

Hotfix TP-1726 Fix permissions for rtp lists

---

config/sync/field.field.node.service.field_other_services.yml

TP-1671 Added published service filter for other services field

---

config/sync/core.entity_form_display.group_content.group_content_type_a689b6d6f98cc.default.yml
config/sync/core.entity_form_display.group_content.organisation-group_membership.default.yml
public/modules/custom/hel_tpm_group/src/Plugin/Field/FieldWidget/GroupRoleRequiredSelectWidget.php

TP-1699 Prevented users from removing all group roles from users

---

public/modules/custom/hel_tpm_general/src/Plugin/Field/FieldFormatter/TimeAndPlaceFormatter.php

TP-1716 Fix hiding empty time and place elements

---

config/sync/pathauto.settings.yml

TP-1729 Removed slash removal from url aliases

---

public/modules/custom/hel_tpm_editorial/js/hel-tpm-datetimepicker.js

TP-1728 Changed first day of week to monday

---

composer.lock

TP-1736 Update drupal/core from 10.4.3 to 10.4.5

---

public/modules/custom/hel_tpm_search/js/jquery.multi-select.js

TP-1740 re-add the checkbox for multiselect

---

config/sync/core.entity_form_display.paragraph.service_time_and_place.default.yml
config/sync/core.entity_view_display.paragraph.service_time_and_place.default.yml
config/sync/core.entity_view_display.paragraph.service_time_and_place.limited_fields.yml
config/sync/field.field.paragraph.service_time_and_place.field_time_additional_info.yml
config/sync/field.storage.paragraph.field_time_additional_info.yml
config/sync/language.content_settings.paragraph.service_time_and_place.yml
public/modules/custom/hel_tpm_forms/hel_tpm_forms.module
public/themes/custom/palvelumanuaali/palvelumanuaali.theme

TP-1732 Created service time additional info field

---

config/sync/language.entity.en.yml
config/sync/language.entity.fi.yml
config/sync/language.entity.sv.yml

TP-1748 Re-ordered languages

---

config/sync/entity_export_csv.entity_export_csv.service_export.yml
public/modules/custom/hel_tpm_contact_info/src/Plugin/FieldTypeExport/ContactInfoExport.php

TP-1750 Add contact info additional info to csv export

---

composer.lock
config/sync/search_api.index.service_search_index.yml
config/sync/search_api.index.service_search_solr_index.yml

SA-CONTRIB-2025-046 Updated solr search api

---

config/sync/purge.plugins.yml
public/modules/custom/hel_tpm_general/src/Plugin/Purge/Queue/UniqueDatabaseQueue.php

TP-1756 Created unique database purge queue to prevent queues fromflooding

---

config/sync/views.view.group_produced_services.yml

TP-1713 Add ID column for Group produced services view

---

config/sync/purge.plugins.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.info.yml
public/modules/custom/hel_tpm_general/hel_tpm_general.services.yml
public/modules/custom/hel_tpm_general/src/Plugin/Purge/Queue/TxBufferUnique.php
public/modules/custom/hel_tpm_general/tests/Functional/UsernameGenerateTest.php
public/modules/custom/hel_tpm_general/tests/Kernel/PreventMailTest.php
public/modules/custom/hel_tpm_general/tests/src/FunctionalJavascript/InlineEntityFormComplexMunicipalitySpecificWidgetTest.php
public/modules/custom/hel_tpm_update_reminder/tests/src/Kernel/ServiceUpdateReminderTest.php

TP-1737 Fixed de-duplication of purge queue items

---

public/modules/custom/hel_tpm_search/hel_tpm_search.module
public/modules/custom/views_exposed_embed/src/Plugin/Field/FieldFormatter/ViewsExposedEmbedFieldDefaultFormatter.php
public/modules/custom/views_exposed_embed/src/Plugin/views/display/ExposedEmbed.php

TP-1762 Hopefully fixed exposed embed filtering

---

config/sync/core.entity_form_display.paragraph.service_time_and_place.default.yml
public/modules/custom/hel_tpm_service_dates/config/schema/hel_tpm_service_dates.schema.yml
public/modules/custom/hel_tpm_service_dates/src/Plugin/Field/FieldWidget/CustomDateRangeWidget.php

TP-1757 Added disable end date selection to custom date range widget

---

config/sync/views.view.service_groups.yml

TP-1697 Added service content filtering for service groups view

---

config/sync/field.field.paragraph.service_time_and_place.field_service_location.yml
config/sync/views.view.service_location_reference.yml

TP-1714 Prevented unpublished service locations from being referenced in service location

---

public/themes/custom/palvelumanuaali/templates/paragraphs/paragraph--service-time-and-place.html.twig

Display additional info

---

config/sync/views.view.group_produced_services.yml
config/sync/views.view.service_groups.yml

TP-1697 Fixed filter permission issues

---

public/modules/custom/hel_tpm_service_dates/hel_tpm_service_dates.module

Fixed time additional info not saving when adding translation

---

translations/sv-interface-translations.po

Fixed translations breaking import

---

config/sync/core.entity_view_display.node.service.internal.yml

TP-1830 remove double header for internal contacts

---

public/modules/custom/hel_tpm_service_dates/src/Plugin/Field/FieldFormatter/WeekdayAndTimeFieldDefaultFormatter.php

TP-1827 Fixed Weekday and time formatter when there is no drupaldatetimeobject

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install

Import database without field migrations. Find a service with translations and that have some values in field_attendance and field_service_execution

TP-1834 Fixed field_service_execution_text and field_attendance_text translation migration

---

config/sync/field_description_tooltip.settings.yml

TP-1842 fix missing tooltips when saving with error

---

config/sync/image.style.card_lift_image.yml
config/sync/image.style.wide_mobile_532x312.yml
config/sync/system.image.gd.yml

TP-1855 adjust image style scaling

---

config/sync/field.field.paragraph.service_time_and_place.field_date_selection.yml

TP-1812 require date type selection

---

public/themes/custom/palvelumanuaali/templates/content/node--landing-page--full.html.twig

Removed hero from landing page template

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install

Added check if db row exists

---

public/modules/custom/hel_tpm_general/hel_tpm_general.install
public/themes/custom/palvelumanuaali/components/05-pages/content-types/landing-page.twig

Hotfix Stage & Production 02.07.2025

---

config/sync/block.block.kirjautuminen.yml

TP-1867 Add translated paths to login button listed pages

---

composer.lock

Installed SA-CONTRIB-2025-088 security updates

---

composer.json
composer.lock
patches/mail-login-quick-fix-3535116.patch

Patched mail login to remove warning message after login

---

config/sync/views.view.taxonomy_term.yml

TP-1871 Add aggregation to taxonomy view to remove duplicates

---

composer.lock
config/sync/block_class.settings.yml
config/sync/language/en/views.view.solr_service_search.yml
config/sync/views.view.solr_service_search.yml

SA-CONTRIB-2025-100

---

public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.info.yml
public/modules/custom/hel_tpm_search_autosuggest/hel_tpm_search_autosuggest.libraries.yml
public/modules/custom/hel_tpm_search_autosuggest/js/hel-tpm-search-autosuggest.js

TP-1901 Refactored autosuggest history updating

---

composer.json
composer.lock
public/modules/custom/hel_tpm_service_stats/src/Plugin/Field/PublishIntervalField.php
public/modules/custom/hel_tpm_service_stats/src/RevisionHistoryService.php

Added patch for node lock translations bug

---

public/modules/custom/hel_tpm_general/hel_tpm_general.module

TP-1931 Fixed service date and time untranslatable field draft issue
